name: Main

on:
  workflow_dispatch:
    inputs:
      featureSet:
        description: 'Choose a feature set to run'
        required: false
        default: 'All'
        type: choice
        options: [ 'All' ]
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  TARGET_ENVIRONMENT: ${{ github.event.inputs.environment }}
  FEATURE_SET: ${{ github.event.inputs.featureSet }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    environment:
      name: ${{ TARGET_ENVIRONMENT }}
    env:
      MY_SUPER_SECRET: ${{ secrets.TARGET_URL }}
      MY_TEST: ${{ secrets.TEST }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - name: Echo input parameters
        run: |
          echo "Selected feature-set: $FEATURE_SET"
          echo "Target environment: $TARGET_ENVIRONMENT"
          echo "Using workflow from: ${{ github.ref_name }}"
          echo "Target URL: $MY_SUPER_SECRET"
          echo "Global env: $MY_TEST"
          echo "Run ID: $RUN_ID"
