name: Main

on:
  workflow_dispatch:

jobs:
 main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check selected Branch
        run: |
          echo "Selected Branch: $github.ref_name"
