name: Main

on:
  workflow_dispatch:

jobs:
 main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: feature/test
          
      - name: Change
        run: mkdir change
        
      - name: Add
        run: git add .
        
      - name: Commit
        run: git commit -m "Changes"
        
      - name: Push
        run: git push
