name: Main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
env: 
  TARGET_ENV: ${{ github.event.inputs.environment }}

jobs:
 main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Access env token
        run: |
          echo ${{ github.event.inputs.environment }}
          echo $TARGET_ENV
          echo $TARGET_ENV.name
          echo $TARGET_ENV.secrets.TARGET_URL
          echo ${{ secrets.TARGET_URL }}
