name: Main

on:
  workflow_dispatch:

jobs:
 main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: feature/test
          
      - name: Change
        run: |
          git config --global user.email "sandra.mainzer@quinscape.de"
          git config --global user.name "Sandra Mainzer"
          git pull
          touch foo.bar
          git add .
          git commit -m "Changes"
          git push
