name: Main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
 main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Echo inputs
        run: |
          echo "Target env: ${{ github.event.inputs.environment }}"
