name: Main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
 main:
    name: Main
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Access env token
        run: env
        
      - name: again
        env:
          MY_SUPER_SECRET: ${{ secrets.TARGET_URL }}
        run: |
          echo "${{ secrets.TARGET_URL }}"
          echo "${{ secrets.TEST }}"
