name: Main

on:
  workflow_dispatch:
    inputs:
      fruit:
        description: 'Which is your favorite fruit?'
        required: true
        default: 'chocolate'
        type: choice
        options:
          - strawberry
          - apple 🍏
          - chocolate
      are_you_happy:
        description: 'True if you are happy'
        required: true
        type: boolean
      name:
        description: 'Tell me your name'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  print-fruit:
    runs-on: ubuntu-latest
    if:  ${{ inputs.are_you_happy }}
    steps:
      - name: Print your favorite fruit to STDOUT
        run: echo ${{ inputs.name }}s favorite fruit is ${{ inputs.fruit }}